[package]
name = "cchess-board-rs"
version = "0.1.0"
edition = "2021"

[dependencies]
tract-onnx = "0.21"
ndarray = "0.16"
image = { version = "0.25", features = ["png", "jpeg"] }
thiserror = "2"
anyhow = "1"
pyo3 = { version = "0.22", features = ["extension-module"] }
numpy = "0.22"

[features]
py = []

[lib]
name = "cchess_board_rs"
crate-type = ["cdylib", "rlib"]

[dev-dependencies]
rand = "0.8"
approx = "0.5"
