[build-system]
requires = ["maturin>=1.0,<2.0"]
build-backend = "maturin"

[project]
name = "cchess-board-rs"
version = "0.1.0"
requires-python = ">=3.8"
classifiers = [
    "Programming Language :: Rust",
    "Programming Language :: Python :: Implementation :: CPython",
]
dependencies = ["numpy>=1.21"]

[tool.maturin]
features = ["py", "pyo3/extension-module"]
module-name = "cchess_board_rs"
